version: '3.9'
x-common_environment: &common_environment
  POSTGRES_PORT: 5432
  POSTGRES_DB: postgres
  POSTGRES_USER_FILE: /run/secrets/postgres_user
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  SQLALCHEMY_TRACK_MODIFICATIONS: True

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2500:2500"
    volumes:
      - ./backend:/app
    environment:
      <<: *common_environment
      DEBUG: True
    depends_on:
      - db
    restart: on-failure
    secrets:
      - postgres_user
      - postgres_password

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    restart: on-failure

  db:
    container_name: db_postgres
    image: postgres:13
    environment:
      <<: *common_environment
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    secrets:
      - postgres_user
      - postgres_password

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "ter@example.com"
      PGADMIN_DEFAULT_PASSWORD: "ter"
    restart: always

  reset_db:
    container_name: reset_db
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python run.py reset_db
    environment:
      <<: *common_environment
      DEBUG: True
    depends_on:
      - db
    restart: on-failure
    secrets:
      - postgres_user
      - postgres_password

  test_backend:
    container_name: test_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -m unittest discover -s tests
    environment:
      <<: *common_environment
      DEBUG: True
    volumes:
      - ./backend:/app
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    file: ./backend/secrets/postgres_user.txt
  postgres_password:
    file: ./backend/secrets/postgres_password.txt

volumes:
  db_data:
