version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2500:2500"
    volumes:
      - ./backend:/app
    environment:
      DEBUG: True
      SQLALCHEMY_TRACK_MODIFICATIONS: True
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    depends_on:
      - db
    restart: on-failure
    secrets:
      - postgres_user
      - postgres_password

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    restart: on-failure

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    file: ./backend/secrets/postgres_user.txt
  postgres_password:
    file: ./backend/secrets/postgres_password.txt

volumes:
  db_data: