FROM python:3.9

WORKDIR /app

COPY requirements.txt ./

RUN python -m pip install --upgrade pip && python -m pip install -r requirements.txt

COPY . .

EXPOSE 2500

CMD ["python", "-m", "unittest", "discover", "-s", "tests"]
